name: Phalcon Test
on: [push]
jobs:
  phalcon:
    runs-on: ubuntu-latest
    steps:
      - name: Composer install
        uses: MilesChou/composer-action@master
        with:
          args: install
      - name: Phalcon action
        uses: mileschou/phalcon-action@master
        with:
          args: php vendor/bin/phpunit
